env:
    global:
        - PACKAGE="poetry" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python        
          python: 3.4
        - os: linux
          language: python
          python: 3.6
        - os: osx
          language: generic


before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - wget "https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py"
    - python get-poetry.py -y
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
      fi
    # install Package Control and package denepdencies
    - sh travis.sh install_package_control

    #create config files
    - source $HOME/.poetry/env
    - poetry config 

script:
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove the following if `coveralls` is not needed
    - pip3 install codecov;
    - codecov

notifications:
    email: false
